### ISSUE TITLE
Embed download links inside the response

### ISSUE THREAD

**Issue by zoeleu** [OskarsMC-Network/velocity-download-api#2]

**Comment by OskarZyg** [comment]
Could anyone suggest how to embed it? I had this idea earlier but I'm not exactly sure about how to add that, and in a non-breaking way.

**Comment by zoeleu** [comment]
> Could anyone suggest how to embed it? I had this idea earlier but I'm not exactly sure about how to add that, and in a non-breaking way.

/:ver/download

returns 301 with redirect to link and json link

**Comment by OskarZyg** [comment]
I'm considering adding something like this:
## `/versions/1.1.8/`
Output: 
```json
{
  // general project metadata here, whatever ill find while making this
}
```

## `/versions/1.1.8/download`
Output: 301 to artifact

##
I might consider adding checksums too. I'll see when I get to it.

**Comment by OskarZyg** [comment]
Take a look at PR #3 and tell me your thoughts please :)

**Comment by zoeleu** [comment]
make it 
- 301
- and send json with link

**Comment by zoeleu** [comment]
I don't know python so I can't help with that

**Comment by OskarZyg** [comment]
> make it
> 
> * 301
> * and send json with link

It already 301's, and I don't think it's good practice to both 301 and send the JSON?

**Comment by zoeleu** [comment]
301 is just a status code. Adding the download link is good for js fetch or other requests that don't follow the links. Its just easier for the user to parse the json.

**Comment by OskarZyg** [comment]
Check the readme for the implementation, for now:
https://velocity-download-api.herokuapp.com/version/3.0.0/
and
https://velocity-download-api.herokuapp.com/version/3.0.0/download
